# Generated by Django 4.1.5 on 2024-04-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_alter_inventory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
